BOARD_TAG        = pro
BOARD_SUB        = 8MHzatmega328
ARDUINO_LIBS     = SPI MySensors DHT IRLib
MONITOR_CMD      = picocom
ARDMK_DIR        = /usr/local/Cellar/arduino-mk/1.5/
MONITOR_BAUDRATE = 115200

include $(ARDMK_DIR)/Arduino.mk
